### ISSUE TITLE
Published Package contains only source

### ISSUE THREAD

**Issue by ovflowd** [jrson83/rehype-extract-excerpt#81]
As mentioned, the `dist` is missing on the published NPM package.

**Comment by jrson83** [comment]
@ovflowd thanks, I will check whats wrong.

**Comment by jrson83** [comment]
@ovflowd I published a new version, can you confirm that the issue has been fixed on `v0.3.1`?

**Comment by ovflowd** [comment]
I wasn't able to test but I can do that later on 👀

**Comment by jrson83** [comment]
> I wasn't able to test but I can do that later on 👀

Did you have time to test yet?
